export const ACTIVE_ROUTES = [
  "GET /",
  "GET /health",
  "GET /worldstate/status",
  "GET /worldstate/translated/:rootKey",
  "GET /worldstate/translated/:rootKey/runs/:runId",
  "GET /worldstate/stats",
  "GET /worldstate/stats/daily",
  // debug — dev only
  "GET /debug/bindings",
  "GET /debug/worldstate/buckets",
  "GET /debug/worldstate/split",
  "GET /debug/worldstate/cache-plan",
  "POST /debug/worldstate/push",
  "GET /debug/worldstate/push-candidates",
  "POST /debug/translations/sync",
  "GET /debug/translations/status",
  "GET /debug/queue/index",
  "GET /debug/r1/index",
  "GET /debug/r2/index",
  "GET /debug/kv/index",
  "GET /debug/d1/index",
] as const;